name: 'Testt'

trigger:
  tags:
    include:
    - v*
  branches:
    exclude:
    - master  

pr: none

pool:
  vmImage: ubuntu-16.04

steps:
- task: Docker@1
  displayName: 'Run build image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: 'Run an image'
    imageName: 'dixaba/qt5-gcc-cross'
    volumes: |
     $(Build.SourcesDirectory):/project/source
     $(Build.ArtifactStagingDirectory):/project/build
    runInBackground: false

- script: awk -v N=2 '/##/&&--N<=0{exit}{print}' changelog.md > $(Build.ArtifactStagingDirectory)/notes
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'tree view'

- task: GitHubRelease@0
  displayName: 'GitHub release'
  inputs:
    gitHubConnection: 'github connection 1'
    repositoryName: 'Dixaba/special-sniffle'
    title: Yaay
    releaseNotesSource: file
    releaseNotesFile: '$(Build.ArtifactStagingDirectory)/notes'
    assets: '$(Build.ArtifactStagingDirectory)/release/*.exe'
